### ISSUE TITLE
Scripts1 need to update

### ISSUE THREAD

**Issue by deyuanyang** [WesterdijkInstitute/BUSCO-fungal-phylogenomics#2]
Hi，

Thanks for sharing these nice scripts， When I use 1_get_assemblies_from_json.py， I found it not work.

Could you update it?

Best  wishes,
Deyuan

**Comment by jorgecnavarrom** [comment]
Hi, I just made some changes to the first script to be compatible with the newest NCBI Datasets software. Hope it works now (worked fine on a small test)

Fair warning: the tool set is getting a bit old. Perhaps projects like https://github.com/jamiemcg/BUSCO_phylogenomics can be a good alternative

**Comment by deyuanyang** [comment]
Thank you very much!

| |
杨德援
|
|
***@***.***
福建省厦门大学
|
---- Replied Message ----
| From | Jorge ***@***.***> |
| Date | 10/07/2024 00:55 |
| To | WesterdijkInstitute/BUSCO-fungal-phylogenomics ***@***.***> |
| Cc | deyuanyang ***@***.***>,
Author ***@***.***> |
| Subject | Re: [WesterdijkInstitute/BUSCO-fungal-phylogenomics] Scripts1 need to update (Issue #2) |

Hi, I just made some changes to the first script to be compatible with the newest NCBI Datasets software. Hope it works now (worked fine on a small test)

Fair warning: the tool set is getting a bit old. Perhaps projects like https://github.com/jamiemcg/BUSCO_phylogenomics can be a good alternative
